services:
  app:
    build:
      dockerfile: docker/php/Dockerfile
    container_name: leader
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    command: >
      /bin/sh -c "composer install && php artisan migrate && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    networks:
        - static-network
  mariadb:
      extends:
          file: docker/mariadb/docker-compose.yml
          service: mariadb

  redis:
      extends:
          file: docker/redis/docker-compose.yml
          service: redis
networks:
  static-network:
    name: static-network
    driver: bridge
